<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Promise</title>
	
</head>
<body>
	
</body>
<script type="text/javascript">

	// promise 创建后立即执行
	var promise = new Promise(function (resolve,reject){
		setTimeout(resolve,5*1000,"123");
	});	


	promise.then(function(value){
		console.log(value);
	});



	// demo2  回调嵌套
	// var p1  = new Promise(function(resolve,reject){
	// 	setTimeout("console.log(123)",2000);		
	// });

	// var p2 = new Promise(function(resolve,reject){

	// 	setTimeout(resolve,2000,"p1");		
	// });

	// p2.then(function(value){
	// 	console.log(123);
	// });


	// 链式调用
	// reject 回调是可选的。
	// then 和 catch
	// 抛出错误可以用 reject 和 throw，一旦执行了resolve ，抛出错误就无效了
	// 抛出错误会具有穿透的效果，下面的代码在第一个then 中抛出错误，最后还是被catch 到了
	// 用 catch 代替then 方法的第 2个参数， 很重要，catch 一定要写
	function getJson(url){
		return new Promise(function(resolve,reject){
			console.log("do somethings");
			resolve(url);
		});
	}


	getJson("baidu.com").then(function(value){
		throw new Error("nullable");
		return getJson(value);
	}).then(function(value){
		console.log(value);
	}).catch(function(error){
		console.log(error);
	});



</script>
</html>